apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: do01vgi5e-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: do01vgi5e-python 
  name: do01vgi5e-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: do01vgi5e-python 
